# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:sqlite:lotofacil.db
spring.datasource.username=
spring.datasource.password=

# ===============================
# LOTOFÁCIL – CAIXA
# ===============================
caixa.lotofacil.base-url=https://servicebus2.caixa.gov.br/portaldeloterias/api/lotofacil
